#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/var/lib/snapd/snap/code/205/usr/share/code/code" "/home/iseeyou/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "" "$@"